services:
  - type: web
    name: tailr-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 